# Generated by Django 5.1 on 2025-11-14 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_category_options_alter_course_instructor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
